version: 2.1

commands:
  hello:
    description: "A very simple command for demonstration purposes"
    matrix:
      parameters:
        say: ["Hello", "Goodbye"]
        name: ["Dave", "Mike"]
    steps:
      - run: echo << parameters.say >> <<parameters.name>>

jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  build_job: # This is our first job.
    docker: # it uses the docker executor
      - image: ubuntu:latest # specifically, a docker image
    steps:
      - checkout # this pulls code down from GitHub
      - run: mkdir my_workspace
      - run: echo "A first hello" > my_workspace/echo-output # This prints "A first hello" to stdout.
      - hello:
      #    say: "Sean"
  test_job:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "testing"
  deploy_job:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "stage deployed!"
workflows:
  main:
    jobs:
      - build_job
      - test_job:
          requires:
            - build_job
      - hold:
          type: approval
          requires:
            - build_job
            - test_job
      - deploy_job:
          requires:
            - hold
          filters:
            branches:
              only:
                - main