version: 2
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  one: # This is our first job.
    docker: # it uses the docker executor
      - image: ubuntu:latest # specifically, a docker image
    steps:
      - checkout # this pulls code down from GitHub
      - run: echo "A first hello" # This prints "A first hello" to stdout.
  two:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: env && pwd
workflows:
  version: 2
  test: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - one
      - two
