version: 2.1

# commands:
#   hello:
#     description: "A very simple command for demonstration purposes"
#     parameters:
#       say:
#         type: string
#         default: "Hello Dave"
#     steps:
#       - run: echo << parameters.say >>

jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  build_job: # This is our first job.
    parameters:
      users:
        type: string
      action:
        type: string
    docker: # it uses the docker executor
      - image: ubuntu:latest # specifically, a docker image
    steps:
      - checkout # this pulls code down from GitHub
      - run echo << parameters.users >>.<< parameters.action >>
#      - run: mkdir my_workspace
#      - run: echo "A first hello" > my_workspace/echo-output # This prints "A first hello" to stdout.
      # - hello:
      #     say: "Sean"
  test_job:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "testing"
  deploy_job:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "stage deployed!"
workflows:
  main:
    jobs:
      - build_job:
          matrix:
            parameters:
              : ["Dave", "Frank", "Bob"]
              action: ["Run", "Read", "Explode"]
      - test_job:
          requires:
            - build_job
      - hold:
          type: approval
          requires:
            - build_job
            - test_job
      - deploy_job:
          requires:
            - hold
          filters:
            branches:
              only:
                - main
  dev:
    jobs:
      - build_job:
          matrix:
            parameters:
              : ["Mary", "Ruby", "Susan"]
              action: ["Run", "Read", "Explode"]
      - test_job:
          requires:
            - build_job
      - hold:
          type: approval
          requires:
            - build_job
            - test_job
      - deploy_job:
          requires:
            - hold
          filters:
            branches:
              only:
                - dev